### ISSUE TITLE
Potential for humidity value reported above 100%?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_SI7021#11]
Speculative, but looks like this:
https://github.com/adafruit/Adafruit_Si7021/issues/10
could happen here as well. Same general math being done with no bounds checking.

**Comment by ladyada** [comment]
yah - if you wanna add a min/max bounds, go ahead - seems like it only happens in very very wet conditions :D

**Comment by caternuson** [comment]
Fixed by #12
