### ISSUE TITLE
Cannot chain together multiple Si7021's on the same bus

### ISSUE THREAD

**Issue by tmbur** [adafruit/Adafruit_CircuitPython_SI7021#23]
This driver assigns the same address each time (0x40). I've been unable to collect data from multiple Si7021's on the same bus using STEMMA QT.

**Comment by anecdata** [comment]
The Si7021 has only the one possible I2C address of 0x40, it's a device limitation not a library limitation. There are other temperature sensors with configurable I2C addresses that would allow more than one per I2C bus (e.g., SHT31-D, MCP9808, HTU31D, PCT2075, TMP117, DPS310, or various BMP/BME breakouts), or you can use an I2C multiplexor (e.g., https://www.adafruit.com/product/2717 or https://www.adafruit.com/product/4704), or you can use multiple I2C busses (if the processor is capable) with one sensor on each.

**Comment by anecdata** [comment]
Closing. @tmbur if you have more detail about the issue that is not answered by the comment above, feel free to re-open.
