### ISSUE TITLE
Heater control not implemented

### ISSUE THREAD

**Issue by aalhard** [adafruit/Adafruit_CircuitPython_SI7021#27]
the proccess in 5.2 of this https://www.silabs.com/documents/public/data-sheets/Si7021-A20.pdf

Arduino has it

**Comment by caternuson** [comment]
Possible new property interface?
```python
# get heater state
si7021.heater_level
# set heater on
si7021.heater_level = 0  # on levels 0 (min) to 15 (max)
# set heater off
si7021.heaterl_level = None
```

**Comment by rsbohn** [comment]
Looks like you can turn the heater on or off without changing the heater level.

**Comment by caternuson** [comment]
Yep, it can. The suggestion above combines turning on/off and setting level in one step, with the goal of trying to be as simple as possible - i.e. it's one line of code.

Would separate on/off and level control be more useful? I think it would require two properties:
```python
si7021.heater_level = 5
si7021.heater_enabled = True
```
