### ISSUE TITLE
RuntimeError: bad USER1 register (2!=3a)

### ISSUE THREAD

**Issue by eleimt** [adafruit/Adafruit_CircuitPython_SI7021#37]
Hello guys
Help me please. I try get temperature use sensor [SI7021](https://media.au.ru/imgs/400x800/b1ec3767f8bf29ecbdd1dfb505998ed6/modul-si7021-s-datchikom-temperatury-i-vlazhnosti-sht21-1-13387136.jpg) with [ESP32U](https://www.e44.com/image.php?url=/images/produits/E/ESP32-DEVKITC-32UE-carte-esp32_13cf5.jpg).

Connecting:
```
ESP32 -> 3.3v  | SI7021 -> VIN
ESP32 -> GND   | SI7021 -> GND
ESP32 -> Pin22 | SI7021 -> SCL
ESP32 -> Pin21 | SI7021 -> SDA
```

My code:
```
import adafruit_si7021

sensor = adafruit_si7021.SI7021(board.I2C())

print('Temperature: {} degrees C'.format(sensor.temperature))
print('Humidity: {}%'.format(sensor.relative_humidity))
```

In the end I get the error:
```
Traceback (most recent call last):
  File "<stdin>", line 18, in <module>
  File "adafruit_si7021/__init__.py", line 160, in __init__
RuntimeError: bad USER1 register (2!=3a)
```

**Comment by caternuson** [comment]
Please contact the maker of the SHT41 breakout.
